### ISSUE TITLE
NewsReader not working on the Py3 images

### ISSUE THREAD

**Issue by neoatomic** [E2OpenPlugins/e2openplugin-NewsReader#3]
The plugin starts in 7.x openatv images and even shows the feed-list, but if you open a feed the windows stay's empty. 
Under 6.4 all works fine, (feeds open and info gets shown in the window) so probably needs some Py3 fixes.

@jbleyel are you able to take a look?

With the EOL of openATV 6.4 i want to migrate friends to >7.0 but they use this plugin daily...

(There is also an 6 year old (closed) commit of mine to add an icon to the plugin on this GIT.)

**Comment by jbleyel** [comment]
I have currently no time, but there are more python developer out there to fix the plugin.

**Comment by neoatomic** [comment]
@MrServo are you able to take a look and add some py3 fixes?

**Comment by MrServo** [comment]
Yes, I will have a look on it!

**Comment by MrServo** [comment]
Done! Sorry for waiting, but other issues had a higher priority
